name: Initialize DashG cloudscape
description: Initialize cloudscape

inputs:
  CLIENT_REPO_PAT:
    description: "PAT to clone to client repos"
  DASHG_CLOUD_INFRA_PAT:
    description: "PAT to access dashg-enterprises cloud infra repos"

runs:
  runs-on: ubuntu-latest
  permissions:
    repository-projects: write
  name: "Clone cloud-deployment and cloud-infrastructure repos."
  steps:
    - run: |
        gh repo create ${{ github.repository_owner }}/cloud-deployment --private --template=https://${{ inputs.DASHG_CLOUD_INFRA_PAT }}@github.com/dashg-enterprises/cloud-deployment.git
        gh repo create ${{ github.repository_owner }}/cloud-infrastructure --private --template=https://${{ inputs.DASHG_CLOUD_INFRA_PAT }}@github.com/dashg-enterprises/cloud-infrastructure.git

      env:
        GH_TOKEN: ${{ inputs.CLIENT_REPO_PAT }}
