name: GH clone

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: |
          # gh repo create ${{ vars.CLIENT_ORG }}/cloud-deployment-test2 --private --template=https://${{ secrets.DASHG_CLOUD_INFRA_PAT }}@github.com/dashg-enterprises/cloud-deployment.git
          # gh repo create ${{ vars.CLIENT_ORG }}/cloud-infrastructure-test2 --private --template=https://${{ secrets.DASHG_CLOUD_INFRA_PAT }}@github.com/dashg-enterprises/cloud-infrastructure.git
          gh auth token
        env:
          GH_TOKEN: ${{ secrets.CLIENT_REPO_PAT }}
