name: GH clone

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: gh repo create cloud-deployment-poc --private --template=https://${{ secrets.CLIENT_REPO_PAT }}@github.com/dashg-enterprises/cloud-deployment.git
        # - run: gh repo create cloud-deployment-poc-test --private
        env:
          GH_TOKEN: ${{ secrets.CLIENT_REPO_PAT }}
