name: Clone necessary cloud templates

on:
  # push:
  #   branches: main
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    name: "Clone cloud-deployment and cloud-infrastructure repos."
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/actions/initialization
        name: Initialize
        id: initialization
        with:
          CLOUD_DEPLOYMENT_PAT: ${{ secrets.CLOUD_DEPLOYMENT_PAT }}
          DASHG_CLOUD_PLATFORM_PAT: ${{ secrets.DASHG_CLOUD_PLATFORM_PAT }}
