name: Clone necessary cloud templates

on:
  # push:
  #   branches: main
  workflow_dispatch:
    inputs:
      repository_owner:
        description: "The org to deploy the cloudscape to"
        required: true
        type: text

jobs:
  comment:
    runs-on: ubuntu-latest
    name: "Clone cloud-deployment and cloud-infrastructure repos."
    steps:
      - uses: actions/checkout@v4
      - run: |
          gh repo create ${{ inputs.repository_owner }}/cloud-deployment --private --template=https://${{ secrets.DASHG_CLOUD_INFRA_PAT }}@github.com/dashg-enterprises/cloud-deployment.git
          gh repo create ${{ inputs.repository_owner }}/cloud-infrastructure --private --template=https://${{ secrets.DASHG_CLOUD_INFRA_PAT }}@github.com/dashg-enterprises/cloud-infrastructure.git
        env:
          GH_TOKEN: ${{ secrets.CLIENT_REPO_PAT }}
