name: Clone necessary cloud templates

on:
  # push:
  #   branches: main
  workflow_dispatch:
    inputs:
      repository_owner:
        description: "The org to deploy the cloudscape to:"
        required: true
        type: text
  repository_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    name: "Clone cloud-deployment and cloud-infrastructure repos."
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo ${{ github.event.client_payload.repository_owner }}
          # gh repo create ${{ github.event.client_payload.repository_owner }}/cloud-deployment-test --private --template=https://${{ secrets.DASHG_CLOUD_INFRA_PAT }}@github.com/dashg-enterprises/cloud-deployment.git
          # gh repo create ${{ github.event.client_payload.repository_owner }}/cloud-infrastructure-test --private --template=https://${{ secrets.DASHG_CLOUD_INFRA_PAT }}@github.com/dashg-enterprises/cloud-infrastructure.git
          # gh repo create ${{ github.event.client_payload.repository_owner }}/workflows-test --private --template=https://github.com/dashg-enterprises/workflows.git
          gh repo create ${{ github.event.client_payload.repository_owner }}/workflows-test-private --private --template=https:///${{ secrets.DASHG_CLOUD_INFRA_PAT }}@github.com/dashg-enterprises/cloud-deployment.git
        env:
          GH_TOKEN: ${{ github.event.client_payload.github_token }}
