name: Clone necessary cloud templates

on:
  # push:
  #   branches: main
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    name: "Clone cloud-deployment and cloud-infrastructure repos."
    steps:
      - run: |
          gh repo create ${{ github.repository_owner }}/cloud-deployment-test --private --template=https://${{ secrets.DASHG_CLOUD_INFRA_PAT }}@github.com/dashg-enterprises/cloud-deployment.git
          gh repo create ${{ github.repository_owner }}/cloud-infrastructure-test --private --template=https://${{ secrets.DASHG_CLOUD_INFRA_PAT }}@github.com/dashg-enterprises/cloud-infrastructure.git

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
