name: mirror Repo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: git
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git --version
          git config -global user.name "DashGs Actions Bot"
          git config -global user.email "brandy.e.garland@gmail.com"
          git init cloud-deployment
          cd cloud-deployment
          git remote add --fetch template https://${{ secrets.DASHG_CLOUD_INFRA_PAT }}@github.com/dashg-enterprises/cloud-deployment.git
          git archive template/main | tar -xf-
          git add .
          git commit -m 'Start with template content'
          # ls
          # git clone --template https://${{ secrets.DASHG_CLOUD_INFRA_PAT }}@github.com/dashg-enterprises/cloud-deployment.git cloud-deployment

    # name: "Mirror cloud-deployment"
    # steps:
    #   - uses: pkgstore/github-action-mirror@main
    #     with:
    #       source_repo: "https://github.com/dashg-enterprises/cloud-infrastructure.git"
    #       source_user: "https://github.com/dashg-enterprises"
    #       source_token: " ${{ secrets.DASHG_CLOUD_INFRA_PAT }}"
    #       target_repo:  "https://github.com/dashg-labs/cloud-infrastructure.git"
    #       target_user:  "https://github.com/dashg-labs"
    #       target_token: "${{ secrets.MIRROR_TARGET_TOKEN_GITHUB }}
    #   - name: Clone dashg-enterprises/cloud-infrastructure PRIVATE repository
    #     uses: GuillaumeFalourd/clone-github-repo-action@v2.3
    #     with:
    #       owner: "dashg-enterprises"
    #       repository: "cloud-infrastructure"
    #       access-token: ${{ secrets.DASHG_CLOUD_INFRA_PAT }}

# "
